<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Du har ikke spesifisert hvor du vil søke. Prøv igjen...',
	602	=>	'Du har ikke spesifisert hva du vil søke etter. Prøv igjen...',
	603	=>	'Vennligs spesifisér litt nærmere',
	604	=>	'Ingen treff. Prøv igjen.',
	605	=>	'Ditt søk fant %d meldinger.',
	606	=>	'Du kan søke i dine meldinger etter angitt tekst. Du kan søke i <u>Fra</u>, <u>Emne</u> og i selve <u>Meldingsteksten</u>. Velg hvilke mapper du vil søke i og klikk <b>Søk</b>. Søket ser ikke forskjell på store og små bokstaber, og ord blir søkt i den rekkefølge de blir skrevet.',
	607	=>	'Meldingstekst',
	608	=>	'Emne',
	609	=>	'Fra',
	610	=>	'To',
	611	=>	'Søk',
	612	=>	'Du har ikke spesifisert mappe(r).',
	613	=>	'Dato',
	614	=>	'velg alle',
	615	=>	'velg ingen'
);
?>
