<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Ja',
	2	=>	'Nei',
	3	=>	'Velg',
	4	=>	'Din nettleser må håndtere JavaScript for å kunne bruke BasiliX effektivt',
	5	=>	'Din nettleser må håndtere CSS for å kunne bruke BasiliX effektivt',
	6	=>	'Din nettleser må håndtere Cookies for å kunne bruke BasiliX effektivt',
	7	=>	'Ukjent',
	8	=>	'Skriv ut',
	9	=>	'Lukk',
	10	=>	'Antall innloggede brukere: %d'
);
?>
