<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Din e-postadresse',
	52	=>	'Passord',
	53	=>	'Log inn',
	54	=>	'Skriv inn ditt passord for å logge på igjen',
	55	=>	'Endre bruker',
	56	=>	'Sikker forbindelse (SSL)',
	57	=>	'Normal forbindelse',
	58	=>	'Vennligst fyll inn alle feltene.',
	59	=>	'Vennligst fyll inn rett e-postadresse.',
	60	=>	'Vennligst fyll inn ditt passord.',
	61	=>	'Feil passord eller e-postadresse.',
	62	=>	'Endre domene'
);
?>
