<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Sie haben nicht angegeben, wo gesucht werden soll. Bitte versuchen Sie es noch einmal.',
	602	=>	'Sie haben keinen Suchbegriff angegeben. Bitte versuchen Sie es noch einmal.',
	603	=>	'Bitte seinen Sie etwas genauer',
	604	=>	'Keine Treffer. Bitte versuchen Sie es noch einmal.',
	605	=>	'Ihre Suche ergab %d Treffer.',
	606	=>	'Sie können Ihre E-Mail Ordner nach E-Mails durchsuchen, die den angegebenen Text enthalten. Sie können im <u>Absender</u>, <u>Betreff</u> und <u>Inhalt</u> suchen. Bitte wählen Sie einen Ordner aus, geben Sie den zu suchenden Begriff ein und klicken dann auf die <b>Suchen</b> Schaltfläche.<br><br>Die Suche beachtet <b>keine</b> Groß-/Kleinschreibung. Geben Sie mehrere Suchbegriffe ein, werden nur E-Mails angezeigt, in der die Begriffe in gegebener Reihenfolge enthalten sind.',
	607	=>	'Inhalt',
	608	=>	'Betreff',
	609	=>	'Absender',
	610	=>	'An',
	611	=>	'Suchen',
	612	=>	'Sie haben keine Ordner zum Durchsuchen ausgewählt.',
	613	=>	'Datum',
	614	=>	'Alle auswählen',
	615	=>	'keinen auswählen'

);
?>
