<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Ja',
	2	=>	'Nein',
	3	=>	'Bitte auswählen',
	4	=>	'You must enable JavaScript for your browser to use BasiliX efficient',
	5	=>	'You must enable CSS support for your browser to use BasiliX efficient',
	6	=>	'You must enable Cookie support for your browser to use BasiliX efficient',
	7	=>	'Unbekannt',
	8	=>	'Drucken',
	9	=>	'Fenster schließen',
	10	=>	'Anzahl der aktuellen Benutzer: %d'
);
?>
