<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Ihre E-Mail Adresse',
	52	=>	'Ihr Passwort',
	53	=>	'Anmelden',
	54	=>	'Bitte Passwort für Re-Login eingeben',
	55	=>	'anderer Benutzer',
	56	=>	'SSL Verbindung',
	57	=>	'Unsichere Verbindung',
	58	=>	'Bitte alle Felder ausfüllen.',
	59	=>	'Bitte geben Sie Ihre korrekte E-Mail Adresse ein.',
	60	=>	'Bitte geben Sie Ihr Passwort ein.',
	61	=>	'Falsches Passwort oder fehlerhafte E-Mail Adresse.',
 	62	=>	'andere Domäne'
);
?>
