<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Anda belum menentukan tempat dilakukan pencarian, silahkan ulangi lagi.',
	602	=>	'Anda belum menentukan apa yang ingin dicari, silahkan ulangi lagi.',
	603	=>	'Tolong lebih rinci',
	604	=>	'Tidak ditemukan, tolong ulangi lagi.',
	605	=>	'Pernyataan anda sesuai dengan pesan %d.',
	606	=>	'Anda dapat mencari pada folder surat, pesan yang mengandung teks tertentu. Pencarian dapat dilakukan pada bagian <u>Dari</u>, <u>Subyek</u> dan <u>Isi</u> dari pesan. Pilih Kotak Surat untuk pencarian, masukkan Kata Kunci, dan klik pada tombol <b>Cari</b>.<br><br>Pencarian <b>tidak</b> case sensitive jadi jika anda memasukkan lebih dari satu kata kunci, hanya pesan yang mengandung kata kunci itu yang akan dicari.',
	607	=>	'Isi',
	608	=>	'Subyek',
	609	=>	'Dari',
	610	=>	'To',
	611	=>	'Cari',
	612	=>	'Andak belum menentukan Kotak Surat untuk pencarian.',
	613	=>	'Tanggal',
	614	=>	'pilih semua',
	615	=>	'jangan pilih semua'
);
?>
