<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Ya',
	2	=>	'Tidak',
	3	=>	'Tolong pilih',
	4	=>	'Anda harus meng-aktifkan JavaScript pada browser untuk menggunakan BasiliX dengan efisien',
	5	=>	'Anda harus meng-aktifkan dukungan CSS pada browser untuk menggunakan BasiliX dengan efisien',
	6	=>	'Anda harus meng-aktifkan dukungan Cookie pada browser untuk menggunakan BasiliX dengan efisien',
	7	=>	'Tidak diketahui',
	8	=>	'Cetak',
	9	=>	'Tutup',
	10	=>	'Pengguna saat ini: %d'
);
?>
