<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Alamat E-Mail anda',
	52	=>	'Password',
	53	=>	'Login',
	54	=>	'Masukkan password anda untuk login kembali',
	55	=>	'Ubah pengguna',
	56	=>	'Koneksi Aman (SSL)',
	57	=>	'Koneksi Normal',
	58	=>	'Tolong isi semua kolom.',
	59	=>	'Tolong isi alamat e-mail anda dengan benar.',
	60	=>	'Tolong masukkan password anda.',
	61	=>	'Password salah atau alamat e-mail tidak ada.',
	62	=>	'Ubah domain'
);
?>
