<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Nevybral jste kde vyhledávat, zkuste to prosím znovu.',
	602	=>	'Nevybral jste co vyhledávat, zkuste to prosím znovu.',
	603	=>	'Prosím buïte více konkrétní',
	604	=>	'Nenalezena žádná schoda, zkuste to prosím znovu.',
	605	=>	'Dotazu vyhovuje %d zpráv.',
	606	=>	'Mùžete prohledávat složky pro zprávy které obsahují zadaný text. Mùžete vyhledávat podle <u>Od</u>, <u>Pøedmìt</u> a <u>Tìlo</u> èástí zpráv. Prosím oznaète složky kde vyhledávat, vložte hledané slovo a stisknìte tlaèítko <b>Vyhledat</b>.<br><br>Vyhledávání <b>nerozlišuje</b> velká a malá písmena. Pokud zadáte více než jedno slovo, pouze zprávy obsahující tato slova v tomto specifickém poøadí budou nalezena.',
	607	=>	'Tìlo',
	608	=>	'Pøedmìt',
	609	=>	'Od',
	610	=>	'To',
	611	=>	'Vyhledat',
	612	=>	'Nevybral jste složku pro prohledávání, zkuste to prosím znovu.',
	613	=>	'Datum',
	614	=>	'Oznaè vše',
	615	=>	'Odznaè vše'
);
?>
