<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Ano',
	2	=>	'Ne',
	3	=>	'Prosím vyberte',
	4	=>	'Musíte povolit v prohlížeèi JavaScript pro používání BasiliX klienta',
	5	=>	'Musíte povolit v prohlížeèi CSS podporu pro používání BasiliX klienta',
	6	=>	'Musíte povolit v prohlížeèi Cookie podporu pro používání BasiliX klienta',
	7	=>	'Neznámý',
	8	=>	'Tisknout',
	9	=>	'Uzavøít okno',
	10	=>	'Pøihlášených uživatelù: %d'
);
?>
