<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Vaše Emailová adresa',
	52	=>	'Heslo',
	53	=>	'Pøihlásit se',
	54	=>	'Prosím napište heslo pro pøihlášení',
	55	=>	'Zmìna uživatele',
	56	=>	'Zabezpeèené pøipojení (mùže být pomalé) (Zatím mimo provoz)',
	57	=>	'Nezabezpeèené pøipojení',
	58	=>	'Prosím vyplòte všechny položky.',
	59	=>	'Prosím vložte korektní Emailovou adresu.',
	60	=>	'Prosím vložte heslo.',
	61	=>	'Nesprávné heslo nebo Emailova adresa.',
	62	=>	'Zmìnit doménu'
);
?>
