<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Od',
	252	=>	'Komu',
	253	=>	'Kopie',
	254	=>	'Pøedmìt',
	255	=>	'Datum',
	256	=>	'Tìlo zprávy',
	257	=>	'Pøílohy:',
	258	=>	'<div align="center"><b>Tìlo zprávy je prázdné</b></div>',
	259	=>	'Požadovaná zpráva nebyla nalezena, možná jste ji právì smazal!',
	260	=>	'Pøedchozí',		// unused
	261	=>	'Následující',		// unused
	262	=>	'Odpovìï',
	263	=>	'Odpovìï všem',
	264	=>	'Smazat',
	265	=>	'Pøeposlat',
	266	=>	'Zobraz hlavièku',
	267	=>	'Není pøedmìt',
	268	=>	'Ulož adresu',
	269	=>	'HTML formátovaná zpráva',
	270	=>	'RFC822 zpráva',
	271	=>	'Status o doruèení',
	272	=>	'Textová zpráva',
	273	=>	'RTF zpráva',
	274	=>	'Neznámá pøíloha',
	275	=>	'Textová zpráva',
	276	=>	'Aplikace',
	277	=>	'Zvukový soubor',
	278	=>	'Obrázek',
	279	=>	'Videoklip',
	280	=>	'PGP Podpis',
	281	=>	'Tìlo zprávy'
);
?>
